---
title: "Modelos de favorabilidad - Aquila_dalberti"
format: docx
editor: visual
---

## Selección de habitat

## Introducción

## Metodología

Para determinar la favorabilidad de la especie en la Comunidad Autónoma de Extremadura, se procedió en primer lugar a identificar aquellas variables predictoras más significativas. Para ello se utilizó la Tasa de descubrimiento falso (FDR) que permite excluir aquellas variables con menor peso en el modelo. Posteriormente se ajustó un modelo linear generalizado por pasos hacia adelante con las variables previamente seleccionadas. Como resultado el modelo incluyó un total de x variables. Con objeto de mejorar la interpretabilidad del modelo, se eliminaron aquellas variables no significativas, por lo que el total de variables incluidas son x. En x variables la relación ha sido (β) positiva, y en y de ellas negativa (en concreto, la orientación sur, la longitud de carreteras y el índice de variabilidad de temperatura). Las x variables con mayor peso en el modelo (Test de Wald), con valores similares muy por encima del resto, han sido X y una mayor Y.

TABLA modelo

Los valores de bondad de ajuste del modelo han indicado un buen ajuste de la capacidad de discriminación de los resultados, con un área bajo la curva superior al 85 % (AUC = 0,865), no encontrando diferencias significativas (HyL \> 0,05) entre lo observado y lo esperado en la prueba de Hosmer y Lemeshow (Tabla 5). La UPR ha establecido pocas zonas con presencia de la especie en cuadrículas con valores de favorabilidad bajos. Por el contrario, los valores de OPR han demostrado la existencia de una supuesta área potencial para la especie en Extremadura, con zonas abundantes con una favorabilidad elevada donde la especie se encuentra actualmente ausente (Tabla 5).

Métricas Evaluación

La matriz de confusión (Tabla 6), en la cual se ha establecido con anterioridad el valor de 0,5 para considerar favorable o desfavorable una cuadrícula; ha puesto de manifiesto que, del total de presencias de la especie, el 19,15 % se corresponden con zonas desfavorables, frente al 80,85 % que se encuentran en zonas favorables. De igual forma, esta matriz ha señalado que el 63,37 % de las cuadrículas del territorio de Extremadura son desfavorables para la especie, al no encontrarse presente la misma.

TABLA matriz confusión

Los resultados han mostrado varios núcleos bien delimitados de alta favorabilidad, especialmente al norte de Badajoz, incluyendo el núcleo de Alburquerque y la Sierra de San Pedro. habiendo obtenido ausencia de zonas con alta favorabilidad (\> 0,8) tanto en la zona norte como en la zona sur de la comunidad (Figura 15.A). En el caso de la visualización de favorabilidad para tres categorías (Figura 15.B), se han podido cuantificar hasta un total de 62 cuadrículas que suponen zonas de alta favorabilidad para la especie (\> 0,8), 249 cuadrículas de favorabilidad intermedia (0,2-0,8) y un total de 205 cuadrículas de baja favorabilidad (\< 0,2).

Mapa Favorabilidad

En el Paso 6 de la regresión logística, más del 75 % (R2 = 0,762; Figura 16) de la favorabilidad total del modelo ha sido explicada por las seis primeras variables que entran en el modelo (Lsi, Tsum, Mat, Conejo, Quesur y Jabali), todas ellas con valores positivos. En este paso, se han obtenido 53 cuadrículas con favorabilidad alta (\> 0,8), que suponen el 85,5 % de las obtenidas en el total del modelo en el último paso; y 147 cuadrículas con valores desfavorables (\< 0,2), que conforman el 71,7 % del total de las mismas en el último paso.

Mapa por pasos

Del total de las variables seleccionadas por el modelo (12 variables), seis han sido relacionadas con factores ambientales bióticos, cuatro con abióticos y solo dos con factores antrópicos (Figura 17 superior). Se puede observar que el número de variables implicadas ha estado en consonancia con el peso que estos factores tienen sobre el modelo final, absorbiendo el 66 % de la variación los factores bióticos, respecto del 33 % de los abióticos y el 13 % de los factores antrópicos. Todas las interacciones entre estos tres factores han tenido un efecto negativo en el modelo, restando peso a cada uno de ellos (Figura 17 inferior).

Gráfico Varianza compartida

## Escenarios futuros y cambio climático

### Introducción

### Metodología

Para determinar el efecto del cambio climático sobre el águila perdicera en Extremadura, se ha utilizado la metodología propuesta por Real et al. (2010) para el cálculo de la favorabilidad climática por unidades espaciales. Para ello, se ha cuantificado la variación entre un escenario presente ---creado mediante la utilización de datos históricos de una serie climática de los últimos años---, y un conjunto de escenarios proyectados a futuro ---establecidos por distintos escenarios temporales, de circulación atmosférica o de emisiones--- (Figura 53).
